CREATE TABLE DB_AGENCY.API_AGENT_SELECTION
(
   REFERENCE_AGENT_ID   NUMBER,
   DATE_CREATE          DATE DEFAULT SYSDATE ,
   USER_CREATE          VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY          DATE,
   USER_MODIFY          VARCHAR2 (20 BYTE),
   JSON_AGENT_FILE      CLOB
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;