CREATE TABLE DB_AGENCY.APP_DEPLOYMENT_LOG
(
  ID            NUMBER,
  TGL_DEPLOY    DATE,
  NO_FPP_TIKET  VARCHAR2(100 BYTE),
  DESCRIPTION   VARCHAR2(255 BYTE),
  DP_VERSION    VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;