CREATE TABLE DB_AGENCY.HIS_AGENT_ENTITY
(
   HIS_AGENT_ENTITY_ID   NUMBER,
   AGENT_ENTITY_ID       NUMBER,
   AGENT_ID              NUMBER,
   DATE_CREATE           DATE DEFAULT SYSDATE ,
   USER_CREATE           VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY           DATE,
   USER_MODIFY           VARCHAR2 (20 BYTE),
   ENTITY_CODE           VARCHAR2 (10 BYTE),
   ENTITY_NO             VARCHAR2 (20 BYTE),
   ENTITY_FILE           VARCHAR2 (255 BYTE),
   ENTITY_FILE_BLOB      BLOB
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;