CREATE TABLE DB_AGENCY.MOV_AGENT_LEGAL
(
   MOVEMENT_LEGAL_ID         NUMBER,
   MOVEMENT_AGENT_ID         NUMBER,
   DATE_CREATE               DATE DEFAULT SYSDATE ,
   USER_CREATE               VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY               DATE,
   USER_MODIFY               VARCHAR2 (20 BYTE),
   LEGAL_CODE                VARCHAR2 (4 BYTE),
   LICENCE_AGENT_NO          VARCHAR2 (10 BYTE),
   LICENCE_AGENT_DATE_FROM   DATE,
   LICENCE_AGENT_DATE_TO     DATE,
   CONTRACT_CODE             VARCHAR2 (3 BYTE),
   CONTRACT_NO               VARCHAR2 (20 BYTE),
   CONTRACT_REPRESENTATIVE   VARCHAR2 (255 BYTE),
   CONTRACT_FILE             VARCHAR2 (255 BYTE),
   CONTRACT_FILE_BLOB        BLOB
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;