CREATE TABLE DB_AGENCY.MOV_AGENT_CONTACT
(
   MOVEMENT_CONTACT_ID   NUMBER,
   MOVEMENT_AGENT_ID     NUMBER,
   DATE_CREATE           DATE DEFAULT SYSDATE ,
   USER_CREATE           VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY           DATE,
   USER_MODIFY           VARCHAR2 (20 BYTE),
   MOBILE_NO             VARCHAR2 (15 BYTE),
   PHONE_NO              VARCHAR2 (15 BYTE),
   EMAIL                 VARCHAR2 (255 BYTE)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;