CREATE TABLE DB_AGENCY.MOV_AGENT_FILE
(
   MOVEMENT_FILE_ID     NUMBER,
   MOVEMENT_AGENT_ID    NUMBER,
   DATE_CREATE          DATE DEFAULT SYSDATE ,
   USER_CREATE          VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY          DATE,
   USER_MODIFY          VARCHAR2 (20 BYTE),
   MOVEMENT_FILE_CODE   VARCHAR2 (3 BYTE),
   MOVEMENT_FILE        VARCHAR2 (255 BYTE),
   MOVEMENT_FILE_BLOB   BLOB
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;