CREATE TABLE DB_AGENCY.MOV_AGENT_ADDRESS
(
   MOVEMENT_ADDRESS_ID    NUMBER,
   MOVEMENT_AGENT_ID      NUMBER,
   DATE_CREATE            DATE DEFAULT SYSDATE ,
   USER_CREATE            VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY            DATE,
   USER_MODIFY            VARCHAR2 (20 BYTE),
   DOMICILE_ADDRESS       VARCHAR2 (4000 BYTE),
   DOMICILE_POSTAL_CODE   VARCHAR2 (10 BYTE),
   DOMICILE_PROVINCE_ID   NUMBER,
   DOMICILE_CITY_ID       NUMBER,
   DOMICILE_STATE_ID      NUMBER,
   ADDRESS                VARCHAR2 (4000 BYTE),
   POSTAL_CODE            VARCHAR2 (10 BYTE),
   PROVINCE_ID            NUMBER,
   CITY_ID                NUMBER,
   STATE_ID               NUMBER
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;