CREATE TABLE DB_AGENCY.MOV_AGENT_POSITION
(
   MOVEMENT_POSITION_ID   NUMBER,
   MOVEMENT_AGENT_ID      NUMBER,
   DATE_CREATE            DATE DEFAULT SYSDATE ,
   USER_CREATE            VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY            DATE,
   USER_MODIFY            VARCHAR2 (20 BYTE),
   COMPANY_CODE           VARCHAR2 (3 BYTE),
   POSITION_CODE          VARCHAR2 (3 BYTE),
   PARENT_AGENT_NO        VARCHAR2 (10 BYTE),
   RECRUITER_AGENT_NO     VARCHAR2 (10 BYTE),
   GROUP_AGENT_CODE       VARCHAR2 (8 BYTE),
   PROPOSAL_AGENT_NO      VARCHAR2 (10 BYTE)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;