CREATE TABLE DB_AGENCY.MOV_AGENT
(
   MOVEMENT_AGENT_ID   NUMBER,
   DATE_CREATE         DATE DEFAULT SYSDATE ,
   USER_CREATE         VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY         DATE,
   USER_MODIFY         VARCHAR2 (20 BYTE),
   AGENT_NO            VARCHAR2 (10 BYTE),
   MOVEMENT_CODE       VARCHAR2 (3 BYTE),
   MOVEMENT_STATUS     NUMBER,
   MOVEMENT_FLAG       VARCHAR2 (3 BYTE),
   MOVEMENT_USER_VER   VARCHAR2 (20 BYTE),
   MOVEMENT_DATE_VER   VARCHAR2 (20 BYTE)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;