CREATE TABLE DB_AGENCY.MOV_AGENT_PERSONAL_DATA
(
   MOVEMENT_PERSONAL_ID   NUMBER,
   MOVEMENT_AGENT_ID      NUMBER,
   DATE_CREATE            DATE DEFAULT SYSDATE ,
   USER_CREATE            VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY            DATE,
   USER_MODIFY            VARCHAR2 (20 BYTE),
   FIRST_NAME             VARCHAR2 (100 BYTE),
   MIDDLE_NAME            VARCHAR2 (100 BYTE),
   LAST_NAME              VARCHAR2 (100 BYTE),
   FRONT_TITLE            VARCHAR2 (100 BYTE),
   REAR_TITLE             VARCHAR2 (100 BYTE),
   PLACE_OF_BIRTH         VARCHAR2 (255 BYTE),
   DATE_OF_BIRTH          DATE,
   PHOTO                  VARCHAR2 (255 BYTE) DEFAULT NULL ,
   PHOTO_BLOB             BLOB,
   GENDER_CODE            VARCHAR2 (1 BYTE),
   RELIGION_CODE          VARCHAR2 (3 BYTE)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;