CREATE TABLE DB_AGENCY.REF_MOVEMENT_FLAG
(
   MOVEMENT_FLAG_ID            NUMBER,
   DATE_CREATE                 DATE DEFAULT SYSDATE ,
   USER_CREATE                 VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY                 DATE,
   USER_MODIFY                 VARCHAR2 (20 BYTE),
   MOVEMENT_FLAG               VARCHAR2 (3 BYTE),
   MOVEMENT_FLAG_DESCRIPTION   VARCHAR2 (255 BYTE),
   MOVEMENT_STEP_NO            NUMBER
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;