CREATE TABLE DB_AGENCY.REF_GENDER
(
  GENDER_ID    NUMBER,
  DATE_CREATE  DATE                             DEFAULT SYSDATE,
  USER_CREATE  VARCHAR2(50 BYTE)                DEFAULT 'DBA',
  DATE_MODIFY  DATE,
  USER_MODIFY  VARCHAR2(20 BYTE),
  GENDER_CODE  VARCHAR2(1 BYTE),
  GENDER_NAME  VARCHAR2(20 BYTE)
) 
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;