CREATE TABLE DB_AGENCY.REF_FILE
(
   FILE_ID            NUMBER,
   DATE_CREATE        DATE DEFAULT SYSDATE ,
   USER_CREATE        VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY        DATE,
   USER_MODIFY        VARCHAR2 (20 BYTE),
   FILE_CODE          VARCHAR2 (3 BYTE),
   FILE_DESCRIPTION   VARCHAR2 (255 BYTE)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;