CREATE TABLE DB_AGENCY.REF_MOVEMENT_STATUS
(
   MOVEMENT_STATUS_ID     NUMBER,
   DATE_CREATE            DATE DEFAULT SYSDATE ,
   USER_CREATE            VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY            DATE,
   USER_MODIFY            VARCHAR2 (20 BYTE),
   MOVEMENT_STATUS        NUMBER,
   MOVEMENT_STATUS_NAME   VARCHAR2 (255 BYTE)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;