CREATE TABLE DB_AGENCY.REF_RELIGION
(
  RELIGION_ID    NUMBER,
  DATE_CREATE    DATE                           DEFAULT SYSDATE,
  USER_CREATE    VARCHAR2(50 BYTE)              DEFAULT 'DBA',
  DATE_MODIFY    DATE,
  USER_MODIFY    VARCHAR2(20 BYTE),
  RELIGION_CODE  VARCHAR2(3 BYTE),
  RELIGION_NAME  VARCHAR2(20 BYTE)
) 
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;