CREATE TABLE DB_AGENCY.REF_LEGAL
(
   LEGAL_ID       NUMBER,
   SELECTION_ID   NUMBER,
   DATE_CREATE    DATE DEFAULT SYSDATE ,
   USER_CREATE    VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY    DATE,
   USER_MODIFY    VARCHAR2 (20 BYTE),
   LEGAL_CODE     VARCHAR2 (3 BYTE),
   LEGAL_NAME     VARCHAR2 (255 BYTE)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;