CREATE TABLE DB_AGENCY.REF_STATE
(
  STATE_ID         NUMBER,
  DATE_CREATE      DATE                         DEFAULT SYSDATE,
  USER_CREATE      VARCHAR2(50 BYTE)            DEFAULT 'DBA',
  DATE_MODIFY      DATE,
  USER_MODIFY      VARCHAR2(20 BYTE),
  STATE_NAME       VARCHAR2(255 BYTE),
  STATE_LONGITUDE  NUMBER,
  STATE_LATITUDE   NUMBER,
  CITY_ID          NUMBER
) 
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;