CREATE TABLE DB_AGENCY.REF_POSITION
(
  POSITION_ID     NUMBER,
  DATE_CREATE     DATE                          DEFAULT SYSDATE,
  USER_CREATE     VARCHAR2(50 BYTE)             DEFAULT 'DBA',
  DATE_MODIFY     DATE,
  USER_MODIFY     VARCHAR2(20 BYTE),
  POSITION_CODE   VARCHAR2(3 BYTE),
  POSITION_NAME   VARCHAR2(20 BYTE),
  POSITION_LEVEL  NUMBER
) 
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;