CREATE TABLE DB_AGENCY.REF_ENTITY
(
   ENTITY_ID      NUMBER,
   DATE_CREATE    DATE DEFAULT SYSDATE ,
   USER_CREATE    VARCHAR2 (50 BYTE) DEFAULT 'DBA' ,
   DATE_MODIFY    DATE,
   USER_MODIFY    VARCHAR2 (20 BYTE),
   ENTTITY_CODE   VARCHAR2 (10 BYTE),
   ENTTITY_NAME   VARCHAR2 (255 BYTE)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;