CREATE TABLE DB_AGENCY.REF_CITY
(
  CITY_ID         NUMBER,
  DATE_CREATE     DATE                          DEFAULT SYSDATE,
  USER_CREATE     VARCHAR2(50 BYTE)             DEFAULT 'DBA',
  DATE_MODIFY     DATE,
  USER_MODIFY     VARCHAR2(20 BYTE),
  CITY_NAME       VARCHAR2(255 BYTE),
  CITY_LONGITUDE  NUMBER,
  CITY_LATITUDE   NUMBER,
  PROVINCE_ID     NUMBER
) 
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;