CREATE TABLE DB_AGENCY.REF_PROVINCE
(
  PROVINCE_ID         NUMBER,
  DATE_CREATE         DATE                      DEFAULT SYSDATE,
  USER_CREATE         VARCHAR2(50 BYTE)         DEFAULT 'DBA',
  DATE_MODIFY         DATE,
  USER_MODIFY         VARCHAR2(20 BYTE),
  PROVINCE_NAME       VARCHAR2(255 BYTE),
  PROVINCE_LONGITUDE  NUMBER,
  PROVINCE_LATITUDE   NUMBER,
  PROVINCE_TIMEZONE   VARCHAR2(10 BYTE),
  COUNTRY_ID          NUMBER
) 
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;