CREATE TABLE DB_AGENCY.REF_AGENT_GROUP
(
  GROUP_AGENT_ID      NUMBER,
  DATE_CREATE         DATE                      DEFAULT SYSDATE,
  USER_CREATE         VARCHAR2(50 BYTE)         DEFAULT 'DBA',
  DATE_MODIFY         DATE,
  USER_MODIFY         VARCHAR2(20 BYTE),
  GROUP_AGENT_CODE    VARCHAR2(8 BYTE),
  GROUP_AGENT_NAME    VARCHAR2(255 BYTE),
  GROUP_AGENT_STATUS  VARCHAR2(1 BYTE),
  CHANNEL_SALES_CODE  VARCHAR2(10 BYTE)
) 
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;