SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM DB_AGENCY.APP_STATISTIC_HIT
--
Insert into DB_AGENCY.APP_STATISTIC_HIT
   (HIT_ID, DATE_HIT, IP_ADDRESS, COUNTRY)
 Values
   (1, TO_DATE('11/09/2019 09:51:34', 'MM/DD/YYYY HH24:MI:SS'), '127.0.0.1', 'INDONESIA');
Insert into DB_AGENCY.APP_STATISTIC_HIT
   (HIT_ID, DATE_HIT, IP_ADDRESS, COUNTRY)
 Values
   (2, TO_DATE('11/09/2019 09:51:53', 'MM/DD/YYYY HH24:MI:SS'), '127.0.0.1', 'INDONESIA');
COMMIT;
