SET DEFINE OFF;
--
--SQL Statement which produced this data:
--  SELECT * FROM DB_AGENCY.APP_ROLE_MENU
--
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (1, 1, 1, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (2, 1, 2, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (3, 1, 3, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (4, 1, 4, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (5, 1, 5, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (6, 1, 6, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (7, 1, 7, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (8, 1, 8, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (9, 1, 9, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (10, 1, 10, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
Insert into DB_AGENCY.APP_ROLE_MENU
   (ROLE_MENU_ID, ROLE_ID, MENU_ID, IS_SELECT, DATE_CREATE, USER_CREATE)
 Values
   (11, 1, 11, 'Y', TO_DATE('11/09/2019 09:34:56', 'MM/DD/YYYY HH24:MI:SS'), 'DBA');
COMMIT;
