@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\API_AGENT_SELECTION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_API_ACCESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_API_ACCESS_DETAIL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_API_ACCESS_TYPE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_API_CLIENT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_API_STATUS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_DEPLOYMENT_LOG.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_MENU.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_MENU_DEL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_MESSAGE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_PROFILE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_PROFILE_DEL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_ROLE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_ROLE_DEL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_ROLE_MENU.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_ROLE_MENU_DEL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_STATISTIC_HIT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_STATISTIC_UNIQUE_HIT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_USER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_USER_ACTIVATION_LOG.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_USER_DEL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_USER_INVALID_UNLOCK.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_USER_LOG.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\APP_USER_SESSION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_ADDRESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_CONTACT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_ENTITY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_LEGAL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_POSITION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_SELECTION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_SELECTION_ADDRESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_SELECTION_CONTACT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_SELECTION_ENTITY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_SELECTION_LEGAL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\HIS_AGENT_SELECTION_POSITION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\LOG_AGENT_PROCESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT_ADDRESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT_CONTACT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT_ENTITY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT_FILE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT_LEGAL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT_LOG.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT_PERSONAL_DATA.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MOV_AGENT_POSITION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MST_AGENT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MST_AGENT_ADDRESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MST_AGENT_CONTACT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MST_AGENT_ENTITY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MST_AGENT_LEGAL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\MST_AGENT_POSITION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REC_AGENT_SELECTION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REC_AGENT_SELECTION_ADDRESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REC_AGENT_SELECTION_CONTACT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REC_AGENT_SELECTION_ENTITY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REC_AGENT_SELECTION_LEGAL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REC_AGENT_SELECTION_POSITION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_AGENT_GROUP.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_CITY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_COMPANY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_CONTRACT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_COUNTRY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_ENTITY.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_FILE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_GENDER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_LEGAL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_MOVEMENT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_MOVEMENT_FLAG.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_MOVEMENT_STATUS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_POSITION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_PROVINCE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_RELIGION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\REF_STATE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Tables\UPL_AGENT_SELECTION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_ACCESS_DETAIL_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_ACCESS_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_ACCESS_TYPE_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_ACTIVATION_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_API_STATUS_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_CLIENT_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_HIT_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_INVALID_UNLOCK_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_KILL_SESSION_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_MENU_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_MESSAGE_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_ROLE_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_ROLE_MENU_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_SESSION_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_UNIQUE_HIT_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_USERLOG_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Sequences\SQ_USER_ID.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_API_ACCESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_API_ACCESS_DETAIL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_API_ACCESS_TYPE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_API_CLIENT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_API_STATUS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_MENU.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_MESSAGE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_ROLE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_ROLE_MENU.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_STATISTIC_HIT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_STATISTIC_UNIQUE_HIT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_USER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_USER_ACTIVATION_LOG.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_USER_INVALID_UNLOCK.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_USER_LOG.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Triggers\TRG_APP_USER_SESSION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Constraints\APP_DEPLOYMENT_LOG_PK.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Functions\F_APP_LAST_TOKEN.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_INVALID_USER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_MENU.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_MENU_CHILD.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_MENU_ROLE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_MENU_ROLE_ALL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_MENU_ROLE_SELECTED.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_MENU_SELECTED.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_MENU_UNSELECTED.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Views\V_APP_ROLE_UNSELECTED.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_DEL_MENU.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_DEL_MENU_ROLE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_DEL_MENU_UNSELECTED.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_DEL_ROLE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_DEL_ROLE_UNSELECTED.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_DEL_USER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_INS_MENU_ROLE_ALL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_INS_ROLE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_INS_STAT_HIT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_INS_STAT_UNIQUE_HIT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_INS_USER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_INS_USER_ACTIVATION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_UNLOCK_USER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_UPD_MENU_ROLE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_UPD_USER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\Procedures\SP_APP_UPD_USER_ACTIVATION.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_API_ACCESS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_API_ACCESS_DETAIL.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_API_ACCESS_TYPE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_API_CLIENT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_API_STATUS.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_MENU.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_MESSAGE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_PROFILE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_ROLE.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_ROLE_MENU.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_STATISTIC_HIT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_STATISTIC_UNIQUE_HIT.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_USER.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\DML\APP_USER_ACTIVATION_LOG.sql 
@C:\implementasi\deployment\DB_AGENCY\Script\Deployment\RECOMPILE.sql  
