CREATE OR REPLACE TRIGGER DB_AGENCY.TRG_APP_API_ACCESS_DETAIL
BEFORE INSERT
ON DB_AGENCY.APP_API_ACCESS_DETAIL 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT SQ_ACCESS_DETAIL_ID.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ACCESS_DETAIL_ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


