/* Formatted on 24/02/2023 11:17:42 (QP5 v5.114.809.3010) */
CREATE OR REPLACE FORCE VIEW DB_AGENCY.V_APP_MENU_UNSELECTED
(
   MENU_ID,
   MENU_NAME,
   LINK
)
AS
     SELECT   MENU_ID, MENU_NAME, LINK
       FROM   APP_MENU
      WHERE   MENU_ID NOT IN (  SELECT   MENU_ID FROM V_APP_MENU_SELECTED)
   ORDER BY   MENU_ID ASC, MENU_NAME ASC;


